server:
  port: 8080

dubbo:
  application:
    name: coolmall-sellgoods-service
    registry: 192.168.100.46:2182

mybatis:
  type-aliases-package: com.coolyk.coolmall.mapper
  mapper-locations: classpath*:mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coolmalldb?useUnicode=true;characeterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver