server:
  port: 8081

dubbo:
  application:
    name: coolmall-sellgoods-service
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://192.168.100.46:2181
  scan:
    base-packages: com.coolyk.coolmail.service

mybatis:
  type-aliases-package: com.coolyk.coolmall.mapper
  mapper-locations: classpath*:mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coolmalldb?useUnicode=true;characeterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: coolmall-sellgoods-service