server:
  port: 8080

dubbo:
  application:
    name: coolmall-sellgoods-web
  registry:
    address: zookeeper://192.168.100.46:2181
  protocol:
    name: dubbo
    port: 20881
  scan:
    base-packages: com.coolyk.coolmail.service

spring:
  application:
    name: coolmall-sellgoods-web